import { defineSchema, f } from "../../../gift-core/index.js";

const TIME = /^([01]?\d|2[0-3]):[0-5]\d$/;
const URL = /^https:\/\/\S+$/i;

export default defineSchema({
  version: 1,
  steps: [
    { id: "baby", title: "El bebé", portalTitle: "¿Quién viene en camino?" },
    { id: "cover", title: "Portada", portalTitle: "La foto de la portada" },
    { id: "message", title: "Anuncio", portalTitle: "El mensaje del anuncio" },
    { id: "event", title: "Evento", portalTitle: "¿Cuándo y dónde es el baby shower?" },
    { id: "gifts", title: "Regalos", portalTitle: "Mesa de regalos" },
    { id: "rsvp", title: "Confirmaciones", portalTitle: "Confirmación de asistencia" },
    { id: "extras", title: "Fotos y música", portalTitle: "Fotos y música (opcional)" },
  ],
  fields: {
    recipientName: f.text({
      label: "Nombre del bebé",
      portalLabel: "¿Cómo se va a llamar?",
      description: "Si todavía no tiene nombre, pon algo como “Baby Pérez”.",
      placeholder: "Emilia",
      required: true,
      max: 24,
      editorStep: "baby",
    }),
    gender: f.select({
      label: "Es niño o niña",
      portalLabel: "¿Es niño o niña?",
      description: "Define toda la paleta: azul para él, rosado para ella, o los dos si aún es sorpresa.",
      options: [
        { value: "boy", label: "Es niño · azul (príncipe)" },
        { value: "girl", label: "Es niña · rosado (princesa)" },
        { value: "surprise", label: "Todavía es sorpresa · azul y rosado" },
      ],
      default: "girl",
      required: true,
      editorStep: "baby",
    }),
    senderName: f.text({
      label: "Los papás",
      portalLabel: "¿Quiénes invitan?",
      placeholder: "Ana y Luis",
      max: 40,
      editorStep: "baby",
    }),
    dueDate: f.date({
      label: "Fecha probable de nacimiento",
      portalLabel: "¿Para cuándo lo esperan? (opcional)",
      editorStep: "baby",
    }),
    coverPhoto: f.image({
      label: "Foto de portada",
      portalLabel: "Una foto de la pancita o la ecografía",
      description: "Aparece dentro del medallón con la corona. Mejor vertical y con buena luz.",
      required: true,
      editorStep: "cover",
    }),
    greeting: f.text({
      label: "Saludo",
      description: "Vacío = según el género (ej. “Un principito viene en camino”).",
      placeholder: "Un principito viene en camino",
      max: 34,
      editorStep: "message",
      customerEditable: false,
    }),
    announceMessage: f.textarea({
      label: "Anuncio",
      portalLabel: "El anuncio",
      default: "Nuestro corazón está por crecer y queremos celebrarlo contigo.",
      max: 140,
      rows: 2,
      editorStep: "message",
    }),
    inviteMessage: f.textarea({
      label: "Invitación",
      portalLabel: "Mensaje de invitación",
      default: "Te esperamos en el baby shower para darle la bienvenida con mucho amor.",
      max: 140,
      rows: 2,
      editorStep: "message",
    }),
    eventDate: f.date({ label: "Fecha del baby shower", required: true, editorStep: "event" }),
    eventTime: f.text({
      label: "Hora",
      description: "Formato 24 horas, ej. 16:00",
      placeholder: "16:00",
      required: true,
      max: 5,
      editorStep: "event",
      validate: (v) => (v && !TIME.test(v) ? "La hora debe tener formato 24 h, por ejemplo 16:00." : undefined),
    }),
    venueName: f.text({ label: "Lugar", placeholder: "Casa de la abuela Rosa", required: true, max: 60, editorStep: "event" }),
    address: f.text({ label: "Dirección", placeholder: "Av. Los Nogales 145, Lima", required: true, max: 120, editorStep: "event" }),
    reference: f.text({ label: "Referencia", placeholder: "Portón blanco, frente al parque", max: 80, editorStep: "event" }),
    mapsUrl: f.text({
      label: "Link de Google Maps",
      description: "Opcional. Si lo dejas vacío se busca la dirección.",
      placeholder: "https://maps.app.goo.gl/…",
      max: 300,
      editorStep: "event",
      validate: (v) => (v && !URL.test(v) ? "Pega un link que empiece con https://" : undefined),
    }),
    dressCode: f.text({
      label: "Código de vestimenta",
      portalLabel: "¿Cómo quieres que vayan vestidos? (opcional)",
      description: "Opcional. Ej. “Ven de celeste” o “Algo cómodo y en tonos pastel”.",
      placeholder: "Ven de celeste",
      max: 60,
      editorStep: "event",
    }),
    giftIdeas: f.list({
      label: "Ideas de regalo",
      itemLabel: "Idea",
      description: "Opcional. Hasta 8 ideas: pañales talla 1, biberones, mantitas…",
      max: 8,
      editorStep: "gifts",
      item: f.text({ label: "Idea", max: 48 }),
    }),
    registryUrl: f.text({
      label: "Link de la mesa de regalos",
      portalLabel: "Link de la mesa de regalos (opcional)",
      placeholder: "https://…",
      max: 300,
      editorStep: "gifts",
      validate: (v) => (v && !URL.test(v) ? "Pega un link que empiece con https://" : undefined),
    }),
    registryNote: f.text({
      label: "Nota sobre los regalos",
      default: "Tu presencia es el mejor regalo, pero si quieres consentir al bebé…",
      max: 90,
      editorStep: "gifts",
    }),
    rsvpEnabled: f.toggle({
      label: "Recibir confirmaciones de asistencia",
      default: true,
      editorStep: "rsvp",
      customerEditable: false,
    }),
    rsvpDeadline: f.date({
      label: "Confirmar hasta",
      portalLabel: "¿Hasta cuándo pueden confirmar? (opcional)",
      editorStep: "rsvp",
    }),
    hostPhone: f.text({
      label: "WhatsApp para dudas",
      portalLabel: "WhatsApp para dudas (opcional)",
      placeholder: "+51 987 654 321",
      max: 20,
      editorStep: "rsvp",
    }),
    photos: f.images({
      label: "Álbum de la dulce espera",
      description: "Opcional. Hasta 8 fotos.",
      max: 8,
      editorStep: "extras",
    }),
    song: f.audio({ label: "Música de fondo", editorStep: "extras" }),
    finalMessage: f.text({
      label: "Mensaje final",
      default: "Gracias por acompañarnos en la espera más linda de nuestra vida.",
      max: 90,
      editorStep: "extras",
    }),
  },
});
