import { defineSchema, f } from "../../../gift-core/index.js";

export default defineSchema({
  version: 1,
  steps: [
    { id: "who", title: "Cumpleañero", portalTitle: "¿Quién cumple años?" },
    { id: "cover", title: "Portada", portalTitle: "Elige la foto de portada" },
    { id: "message", title: "Mensaje", portalTitle: "Escribe tu mensaje" },
    { id: "moments", title: "Momentos", portalTitle: "Sube sus mejores momentos" },
    { id: "music", title: "Canción", portalTitle: "Su canción" },
    { id: "friends", title: "Mensajes de amigos", portalTitle: "¿Quieres agregar mensajes de amigos?" },
    { id: "style", title: "Estilo" },
  ],
  fields: {
    recipientName: f.text({
      label: "Nombre del cumpleañero/a",
      portalLabel: "¿Cómo se llama?",
      placeholder: "Sofía",
      required: true,
      max: 30,
      editorStep: "who",
    }),
    senderName: f.text({
      label: "De parte de",
      portalLabel: "¿Quién envía el regalo?",
      placeholder: "Tus amigos",
      max: 40,
      editorStep: "who",
    }),
    birthDate: f.date({
      label: "Fecha de cumpleaños",
      portalLabel: "¿Cuándo es su cumpleaños?",
      description: "Opcional. Muestra una cuenta regresiva hasta su día.",
      editorStep: "who",
    }),
    coverPhoto: f.image({
      label: "Foto de portada",
      portalLabel: "Una foto donde salga feliz",
      description: "Se ve a pantalla completa. Mejor si es vertical.",
      required: true,
      editorStep: "cover",
    }),
    coverVideo: f.video({
      label: "Video de portada",
      description: "Opcional. Se reproduce en silencio detrás del título.",
      editorStep: "cover",
    }),
    greeting: f.text({
      label: "Saludo",
      default: "¡Feliz cumpleaños",
      max: 30,
      editorStep: "cover",
      customerEditable: false,
    }),
    introTitle: f.text({
      label: "Título del mensaje",
      default: "Hoy celebramos tu vida",
      max: 40,
      editorStep: "message",
      customerEditable: false,
    }),
    message: f.textarea({
      label: "Mensaje principal",
      portalLabel: "Tu mensaje",
      placeholder: "Gracias por ser esa persona tan increíble…",
      required: true,
      min: 10,
      max: 500,
      rows: 5,
      editorStep: "message",
    }),
    photoCaption: f.text({
      label: "Frase de la foto",
      description: "Escrita a mano sobre la primera foto.",
      default: "Siempre tú",
      max: 28,
      editorStep: "message",
    }),
    photos: f.images({
      label: "Galería de momentos",
      portalLabel: "Sus fotos",
      required: true,
      min: 1,
      max: 20,
      editorStep: "moments",
    }),
    song: f.audio({ label: "Canción", editorStep: "music" }),
    songTitle: f.text({ label: "Nombre de la canción", placeholder: "Good as Hell", max: 60, editorStep: "music" }),
    songArtist: f.text({ label: "Artista", placeholder: "Lizzo", max: 60, editorStep: "music" }),
    noteMessage: f.textarea({
      label: "Nota junto a la canción",
      default: "Que este nuevo año te traiga todo lo bonito que mereces.",
      max: 160,
      rows: 3,
      editorStep: "music",
    }),
    noteSignature: f.text({ label: "Firma de la nota", default: "Te queremos", max: 30, editorStep: "music" }),
    friendMessages: f.list({
      label: "Mensajes de amigos y familia",
      description: "Opcional. Aparecen en la pestaña Mensajes.",
      itemLabel: "Mensaje",
      max: 20,
      editorStep: "friends",
      item: f.group({
        fields: {
          name: f.text({ label: "Nombre", required: true, max: 40 }),
          message: f.textarea({ label: "Mensaje", required: true, max: 240, rows: 3 }),
        },
      }),
    }),
    style: f.select({
      label: "Estilo",
      options: [
        { value: "classic", label: "Clásico · elegante y atemporal" },
        { value: "modern", label: "Moderno · colores vibrantes" },
        { value: "minimal", label: "Minimalista · limpio y sofisticado" },
      ],
      default: "classic",
      editorStep: "style",
      customerEditable: false,
    }),
  },
});
