import { defineSchema, f } from "../../../gift-core/index.js";

const TIME = /^([01]?\d|2[0-3]):[0-5]\d$/;
const URL = /^https:\/\/\S+$/i;

export default defineSchema({
  version: 1,
  steps: [
    { id: "who", title: "Cumpleañero", portalTitle: "¿Quién cumple años?" },
    { id: "cover", title: "Portada y tema", portalTitle: "Elige su foto" },
    { id: "message", title: "Mensaje", portalTitle: "El mensaje de la invitación" },
    { id: "event", title: "Evento", portalTitle: "¿Cuándo y dónde es la fiesta?" },
    { id: "rsvp", title: "Confirmaciones", portalTitle: "Confirmación de asistencia" },
    { id: "extras", title: "Fotos y música", portalTitle: "Fotos y música (opcional)" },
  ],
  fields: {
    recipientName: f.text({
      label: "Nombre del cumpleañero/a",
      portalLabel: "¿Cómo se llama?",
      placeholder: "Mateo",
      required: true,
      max: 20,
      editorStep: "who",
    }),
    age: f.number({
      label: "Años que cumple",
      portalLabel: "¿Cuántos años cumple?",
      required: true,
      min: 1,
      max: 18,
      editorStep: "who",
    }),
    senderName: f.text({
      label: "Organiza",
      portalLabel: "¿Quién invita? (opcional)",
      placeholder: "Familia Pérez",
      max: 40,
      editorStep: "who",
    }),
    coverPhoto: f.image({
      label: "Foto del cumpleañero",
      portalLabel: "Una foto de su carita feliz",
      description: "Aparece dentro del marco de cómic. Mejor de frente y con buena luz.",
      required: true,
      editorStep: "cover",
    }),
    theme: f.select({
      label: "Tema",
      options: [
        { value: "heroes", label: "Superhéroes · acción y aventura" },
        { value: "princess", label: "Princesas · mágico y encantador" },
        { value: "dinos", label: "Dinosaurios · divertido y prehistórico" },
        { value: "space", label: "Espacio · explora el universo" },
      ],
      default: "heroes",
      editorStep: "cover",
      customerEditable: false,
    }),
    greeting: f.text({
      label: "Saludo",
      description: "Vacío = según el tema (ej. ¡Hola Héroe!).",
      placeholder: "¡Hola Héroe!",
      max: 28,
      editorStep: "message",
      customerEditable: false,
    }),
    inviteMessage: f.textarea({
      label: "Invitación",
      portalLabel: "Mensaje de invitación",
      default: "Te invito a celebrar mi súper cumpleaños",
      max: 120,
      rows: 2,
      editorStep: "message",
    }),
    missionText: f.textarea({
      label: "Frase especial",
      default: "Será una misión muy especial y quiero que estés ahí.",
      max: 120,
      rows: 2,
      editorStep: "message",
    }),
    eventDate: f.date({ label: "Fecha de la fiesta", required: true, editorStep: "event" }),
    eventTime: f.text({
      label: "Hora",
      description: "Formato 24 horas, ej. 16:00",
      placeholder: "16:00",
      required: true,
      max: 5,
      editorStep: "event",
      validate: (v) => (v && !TIME.test(v) ? "La hora debe tener formato 24 h, por ejemplo 16:00." : undefined),
    }),
    venueName: f.text({ label: "Lugar", placeholder: "Salón Aventuras", required: true, max: 60, editorStep: "event" }),
    address: f.text({ label: "Dirección", placeholder: "Calle Diversión 123, Lima", required: true, max: 120, editorStep: "event" }),
    reference: f.text({ label: "Referencia", placeholder: "Frente al parque", max: 80, editorStep: "event" }),
    mapsUrl: f.text({
      label: "Link de Google Maps",
      description: "Opcional. Si lo dejas vacío se busca la dirección.",
      placeholder: "https://maps.app.goo.gl/…",
      max: 300,
      editorStep: "event",
      validate: (v) => (v && !URL.test(v) ? "Pega un link que empiece con https://" : undefined),
    }),
    rsvpEnabled: f.toggle({
      label: "Recibir confirmaciones de asistencia",
      default: true,
      editorStep: "rsvp",
      customerEditable: false,
    }),
    rsvpDeadline: f.date({
      label: "Confirmar hasta",
      portalLabel: "¿Hasta cuándo pueden confirmar? (opcional)",
      editorStep: "rsvp",
    }),
    hostPhone: f.text({
      label: "WhatsApp para dudas",
      portalLabel: "WhatsApp para dudas (opcional)",
      placeholder: "+51 987 654 321",
      max: 20,
      editorStep: "rsvp",
    }),
    photos: f.images({
      label: "Álbum de aventuras",
      description: "Opcional. Hasta 8 fotos.",
      max: 8,
      editorStep: "extras",
    }),
    song: f.audio({ label: "Música de fondo", editorStep: "extras" }),
    finalMessage: f.text({
      label: "Mensaje final",
      default: "¡Nos vemos pronto para vivir esta aventura!",
      max: 70,
      editorStep: "extras",
    }),
  },
});
