import { defineSchema, f } from "../../../gift-core/index.js";

export default defineSchema({
  version: 1,
  steps: [
    { id: "who", title: "Para quién es", portalTitle: "¿Para quién es la carta?" },
    { id: "letter", title: "La carta", portalTitle: "Escribe tu carta" },
    { id: "memories", title: "Recuerdos", portalTitle: "Elige sus recuerdos" },
    { id: "music", title: "Música", portalTitle: "Elige su canción" },
    { id: "ending", title: "Final", portalTitle: "Unas últimas palabras" },
  ],
  fields: {
    recipientName: f.text({
      label: "Para",
      portalLabel: "¿Cómo se llama?",
      placeholder: "Sofía",
      required: true,
      max: 40,
      editorStep: "who",
    }),
    senderName: f.text({
      label: "De",
      portalLabel: "¿Quién firma la carta?",
      placeholder: "Mateo",
      required: true,
      max: 40,
      editorStep: "who",
    }),
    teaser: f.text({
      label: "Frase del sobre",
      description: "Lo primero que ve, antes de abrir.",
      default: "Tengo algo para ti",
      placeholder: "Tengo algo para ti",
      max: 48,
      editorStep: "letter",
      customerEditable: false,
    }),
    letter: f.textarea({
      label: "Carta",
      portalLabel: "Tu carta",
      description: "Separa los párrafos con una línea en blanco.",
      placeholder: "Desde el día que te conocí…",
      required: true,
      min: 40,
      max: 1800,
      rows: 8,
      editorStep: "letter",
    }),
    closing: f.text({
      label: "Despedida",
      default: "Con todo mi amor",
      placeholder: "Con todo mi amor",
      max: 48,
      editorStep: "letter",
    }),
    letterDate: f.date({
      label: "Fecha de la carta",
      portalLabel: "¿Qué fecha le ponemos?",
      description: "Opcional. Aparece arriba de la carta.",
      editorStep: "letter",
    }),
    memories: f.images({
      label: "Recuerdos",
      portalLabel: "Sus fotos juntos",
      description: "Entre 3 y 8 fotos. Caen sobre la mesa después de leer la carta.",
      required: true,
      min: 3,
      max: 8,
      editorStep: "memories",
    }),
    song: f.audio({
      label: "Canción",
      description: "Empieza a sonar al abrir el sobre.",
      editorStep: "music",
    }),
    finalMessage: f.textarea({
      label: "Mensaje final",
      portalLabel: "Una frase para terminar",
      default: "Gracias por existir.",
      placeholder: "Gracias por existir.",
      max: 180,
      rows: 2,
      editorStep: "ending",
    }),
    sealColor: f.select({
      label: "Color del sello",
      options: [
        { value: "wine", label: "Vino" },
        { value: "gold", label: "Dorado" },
        { value: "rose", label: "Rosa" },
      ],
      default: "wine",
      editorStep: "ending",
      customerEditable: false,
    }),
  },
});
