import { defineSchema, f } from "../../../gift-core/index.js";

export default defineSchema({
  version: 1,
  steps: [
    { id: "who", title: "Para quién es", portalTitle: "¿Para quién es la sorpresa?" },
    { id: "message", title: "Mensaje", portalTitle: "Escribe tu mensaje" },
    { id: "photos", title: "Fotos", portalTitle: "Sube sus fotos favoritas" },
    { id: "music", title: "Música", portalTitle: "Elige su canción" },
    { id: "extras", title: "Extras" },
  ],
  fields: {
    recipientName: f.text({
      label: "Nombre de quien recibe",
      portalLabel: "¿Cómo se llama?",
      placeholder: "Andrea",
      required: true,
      max: 40,
      editorStep: "who",
    }),
    senderName: f.text({
      label: "De parte de",
      portalLabel: "¿Quién lo envía?",
      placeholder: "Diego",
      max: 40,
      editorStep: "who",
    }),
    title: f.text({
      label: "Título",
      description: "Aparece al abrir el regalo.",
      placeholder: "Flores amarillas para ti",
      default: "Flores amarillas para ti",
      max: 60,
      editorStep: "message",
      customerEditable: false,
    }),
    message: f.textarea({
      label: "Mensaje",
      portalLabel: "Tu mensaje",
      description: "Escríbelo como si se lo dijeras en persona.",
      placeholder: "Porque cada día a tu lado florece algo nuevo…",
      required: true,
      min: 10,
      max: 600,
      rows: 5,
      editorStep: "message",
    }),
    importantDate: f.date({
      label: "Fecha especial",
      portalLabel: "¿Una fecha importante? (opcional)",
      description: "El día que se conocieron, su aniversario…",
      editorStep: "message",
    }),
    photos: f.images({
      label: "Fotos",
      portalLabel: "Tus fotos",
      description: "Aparecen como recuerdos entre las flores.",
      required: true,
      min: 1,
      max: 12,
      editorStep: "photos",
    }),
    song: f.audio({
      label: "Canción",
      portalLabel: "Canción (opcional)",
      description: "Sonará al abrir el regalo.",
      editorStep: "music",
    }),
    videos: f.list({
      label: "Videos",
      description: "Opcional. Se muestran al final.",
      itemLabel: "Video",
      max: 4,
      item: f.video({ label: "Video" }),
      editorStep: "extras",
      customerEditable: false,
    }),
  },
});
